version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-school
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql

  api:
    build: .
    container_name: school-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpassword
      DB_NAME: school_db
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["node", "src/server.js"]

volumes:
  mysql_data:
