version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-school
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql

  api:
    build: .
    container_name: school-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: ["node", "src/server.js"]

volumes:
  mysql_data:
